version: '3'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins
    privileged: true
    environment:
      - DOCKER_HOST=tcp://host.docker.internal:2375  # Usar host.docker.internal para Windows
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Montar el socket de Docker
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins_network
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube:lts
    container_name: sonarqube
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    ports:
      - "9000:9000"
    networks:
      - jenkins_network
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: sonarqube_db
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - jenkins_network

networks:
  jenkins_network:

volumes:
  jenkins_home:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  db_data:
